# *******************************************************************************
# Copyright (c) 2024 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0
#
# SPDX-License-Identifier: Apache-2.0
# *******************************************************************************
name: "Automotive Image Builder"
description: "Run Automotive Image Builder (AIB)"
inputs:
  manifest:
    description: "Image file manifest to use"
    required: true
  distro:
    description: "Distro to use when generaring an image"
    default: "autosd10"
  mode:
    description: "Which image mode to use (image or package)"
    default: "package"
  target:
    description: "The targeted platform to build against"
    default: "qemu"
  export:
    description: "Image file format to export to"
    default: "qcow2"
  disk_path:
    description: "Output disk path generated by aib"
    required: true
  extra_args:
    description: "any extra args to be included (--define-file, etc)"
  oci_path:
    description: "Container runtime path"
    default: "/usr/bin/podman"
  base_dir:
    description: "Working dir to run build commands from"
    default: "."

runs:
  using: "composite"
  steps:
    - name: Preflight Checks
      shell: bash
      run: |
        stat ${{ inputs.oci_path }}

    - name: Download builder script
      shell: bash
      run: |
        curl -o /tmp/auto-image-builder.sh "https://gitlab.com/lrossett/automotive-image-builder/-/raw/script-fix/auto-image-builder.sh?ref_type=heads"
        chmod +x /tmp/auto-image-builder.sh

    - name: Build AIB image
      shell: bash
      run: |
        sudo /tmp/auto-image-builder.sh build-deprecated \
        --distro ${{ inputs.distro }} \
        --mode ${{ inputs.mode }} \
        --target ${{ inputs.target }} \
        --export ${{ inputs.export }} \
        ${{ inputs.extra_args }} \
        ${{ inputs.manifest }} \
        ${{ inputs.disk_path }}
      working-directory: "${{ inputs.base_dir }}"

    - name: Post Build
      shell: bash
      run: |
        sudo chown $(id -u) disk.qcow2
      working-directory: "${{ inputs.base_dir }}"
